# Generated by Django 4.2.30 on 2026-04-22 16:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('operateur', models.CharField(choices=[('orange', 'Orange Money'), ('mtn', 'MTN MoMo'), ('wave', 'Wave')], default='orange', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirme'), ('failed', 'Echoue'), ('refunded', 'Rembourse')], default='pending', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
