# Generated by Django 4.2.30 on 2026-04-22 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptabilite', '0001_initial'),
        ('scolarite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='scolarite.etudiant'),
        ),
    ]
