# Generated by Django 4.2 on 2026-05-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='operateur',
            field=models.CharField(choices=[('orange', 'Orange Money'), ('mtn', 'MTN MoMo'), ('moov', 'Moov Money'), ('wave', 'Wave')], default='orange', max_length=20),
        ),
    ]
