# Generated by Django 4.2.30 on 2026-04-22 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0002_mediaitem_description_mediaitem_video_type_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_avatars', to='mediatheque.mediaitem'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('direction', 'Direction'), ('staff', 'Staff'), ('compta', 'Comptabilite'), ('etudiant', 'Etudiant'), ('enseignant', 'Enseignant')], default='etudiant', max_length=20),
        ),
    ]
