# Generated by Django 4.2 on 2026-05-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_avatar_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('direction', 'Direction'), ('staff', 'Staff'), ('compta', 'Comptabilite'), ('etudiant', 'Etudiant'), ('enseignant', 'Enseignant'), ('chauffeur', 'Chauffeur')], default='etudiant', max_length=20),
        ),
    ]
