# Generated by Django 4.2.30 on 2026-04-22 16:22

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mediatheque', '0002_mediaitem_description_mediaitem_video_type_and_more'),
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('pays', models.CharField(choices=[('BJ', 'Benin'), ('BF', 'Burkina Faso'), ('CI', "Cote d'Ivoire"), ('ML', 'Mali'), ('MR', 'Mauritanie'), ('NE', 'Niger'), ('SN', 'Senegal'), ('TG', 'Togo')], max_length=5)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=200)),
                ('rang_promotion', models.PositiveIntegerField(default=1)),
                ('solde_scolarite', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='formations.filiere')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_photos', to='mediatheque.mediaitem')),
            ],
            options={
                'ordering': ['matricule'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type_document', models.CharField(choices=[('certificat', 'Certificat de scolarite'), ('releve', 'Releve de notes'), ('bulletin', 'Bulletin')], max_length=20)),
                ('semester', models.CharField(blank=True, max_length=5)),
                ('academic_year', models.CharField(blank=True, max_length=10)),
                ('file', models.FileField(blank=True, upload_to='documents/%Y/%m/')),
                ('is_generated', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='scolarite.etudiant')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('year_start', models.PositiveIntegerField()),
                ('year_end', models.PositiveIntegerField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='formations.filiere')),
            ],
            options={
                'ordering': ['-year_start', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=200)),
                ('coefficient', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('credits', models.PositiveIntegerField(default=3)),
                ('note', models.DecimalField(decimal_places=2, max_digits=5)),
                ('semestre', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('S3', 'Semestre 3'), ('S4', 'Semestre 4')], max_length=5)),
                ('annee_academique', models.CharField(max_length=10)),
                ('is_validated', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='scolarite.etudiant')),
            ],
            options={
                'ordering': ['annee_academique', 'semestre', 'matiere'],
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'General'), ('filiere', 'Ma filiere'), ('promotion', 'Ma promotion'), ('stages', 'Offres stages/emplois')], default='general', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('replies_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='etudiant',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='scolarite.promotion'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmploiDuTempsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=200)),
                ('enseignant', models.CharField(blank=True, max_length=200)),
                ('salle', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('cours', 'Cours'), ('td', 'TD'), ('examen', 'Examen'), ('ferie', 'Ferie')], default='cours', max_length=10)),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='scolarite.promotion')),
            ],
            options={
                'ordering': ['debut'],
            },
        ),
    ]
