# Generated by Django 4.2.30 on 2026-04-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='config/')),
                ('logo_alt', models.CharField(default='Logo EMSP', max_length=100)),
                ('site_name', models.CharField(default='EMSP', max_length=100)),
                ('slogan', models.CharField(blank=True, max_length=255)),
                ('phone_1', models.CharField(default='+225 27 21 21 45 60', max_length=30)),
                ('phone_2', models.CharField(blank=True, max_length=30)),
                ('email_contact', models.EmailField(default='contact@emsp.int', max_length=254)),
                ('email_info', models.EmailField(default='info@emsp.int', max_length=254)),
                ('address', models.TextField(default='Treichville, Zone 3, Km4, Boulevard de Marseille, Abidjan')),
                ('about_text', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('footer_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
    ]
