# Generated by Codex on 2026-04-22

from django.db import migrations


def seed_site_config(apps, schema_editor):
    SiteConfig = apps.get_model("core", "SiteConfig")
    site_config, _ = SiteConfig.objects.get_or_create(
        pk=1,
        defaults={
            "site_name": "EMSP",
        },
    )
    site_config.site_name = "EMSP"
    site_config.logo_alt = "Logo EMSP"
    site_config.slogan = (
        "Former les talents postaux et numeriques de la sous-region."
    )
    site_config.about_text = (
        "L'Ecole Multinationale Superieure des Postes accompagne les administrations "
        "postales, les services financiers et les acteurs du numerique avec des "
        "cursus professionnalisants, ancres dans les besoins des Etats membres."
    )
    site_config.footer_text = (
        "Institution intergouvernementale de reference pour la formation postale "
        "et la transformation numerique en Afrique."
    )
    site_config.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_contactmessage"),
    ]

    operations = [
        migrations.RunPython(seed_site_config, migrations.RunPython.noop),
    ]
