# Generated by Codex on 2026-04-22

from django.db import migrations, models


def seed_homepage_banner(apps, schema_editor):
    SiteConfig = apps.get_model("core", "SiteConfig")
    site_config, _ = SiteConfig.objects.get_or_create(pk=1)
    if not site_config.homepage_banner_text:
        site_config.homepage_banner_text = (
            "Infos EMSP : actualites institutionnelles, calendrier academique, "
            "concours et annonces officielles modifiables depuis l'administration."
        )
    site_config.show_homepage_banner = True
    site_config.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_seed_site_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="homepage_banner_text",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="show_homepage_banner",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(seed_homepage_banner, migrations.RunPython.noop),
    ]
