# Generated by Django 4.2.30 on 2026-04-22 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediatheque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('niveau', models.CharField(choices=[('FSP', 'Formation Superieure Postale'), ('LICENCE', 'Licence FS-MENUM'), ('MASTER', 'Master FS-MENUM'), ('FCQ', 'Formation Certifiante')], max_length=20)),
                ('duree', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediatheque.mediaitem')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
