# Generated by Codex on 2026-04-22

from django.db import migrations


FORMATIONS = [
    {
        "code": "ADM",
        "nom": "Cycle des Administrateurs",
        "niveau": "FSP",
        "duree": "Cycle professionnel",
        "ordre": 1,
        "description": (
            "Formation superieure postale de haut niveau destinee aux cadres de direction "
            "des administrations postales et des services financiers. Le cycle porte sur "
            "la strategie, la gouvernance, le pilotage des reformes et la cooperation "
            "institutionnelle a l'echelle regionale."
        ),
    },
    {
        "code": "INP",
        "nom": "Cycle des Inspecteurs",
        "niveau": "FSP",
        "duree": "Cycle professionnel",
        "ordre": 2,
        "description": (
            "Parcours professionnalisant pour les cadres moyens charges du pilotage "
            "operationnel, du controle interne et de la supervision des services "
            "financiers postaux."
        ),
    },
    {
        "code": "CTR",
        "nom": "Cycle des Controleurs",
        "niveau": "FSP",
        "duree": "Cycle professionnel",
        "ordre": 3,
        "description": (
            "Formation technique axee sur la maitrise de l'exploitation postale, le "
            "controle des procedures et l'amelioration de la qualite de service."
        ),
    },
    {
        "code": "LNUM",
        "nom": "Logistique et Numerique",
        "niveau": "LICENCE",
        "duree": "Bac+3 - Licence professionnelle",
        "ordre": 10,
        "description": (
            "Licence professionnelle dediee a la chaine logistique connectee et aux "
            "outils numeriques de pilotage. Admission en L1 : baccalaureat et concours "
            "d'entree. Admission en L3 : BAC+2 en sciences economiques/gestion ou BTS "
            "tertiaire (finance, logistique, transport) sur concours."
        ),
    },
    {
        "code": "FDIG",
        "nom": "Finance Digitale",
        "niveau": "LICENCE",
        "duree": "Bac+3 - Licence professionnelle",
        "ordre": 11,
        "description": (
            "Licence professionnelle pour maitriser les outils, services et modeles de "
            "la finance digitale. Admission en L1 : baccalaureat et concours d'entree. "
            "Admission en L3 : BAC+2 en economie/gestion ou BTS tertiaire oriente "
            "finance, banque ou logistique sur concours."
        ),
    },
    {
        "code": "MDIG",
        "nom": "Marketing Digital",
        "niveau": "LICENCE",
        "duree": "Bac+3 - Licence professionnelle",
        "ordre": 12,
        "description": (
            "Licence professionnelle centree sur les strategies marketing, la "
            "communication numerique et l'acquisition digitale. Admission en L1 : "
            "baccalaureat et concours d'entree. Admission en L3 : BAC+2 ou BTS "
            "tertiaire sur concours."
        ),
    },
    {
        "code": "DSER",
        "nom": "Digitalisation des Services",
        "niveau": "LICENCE",
        "duree": "Bac+3 - Licence professionnelle",
        "ordre": 13,
        "description": (
            "Licence professionnelle orientee vers la transformation des processus, "
            "l'amelioration du service et la digitalisation des organisations. "
            "Admission en L1 : baccalaureat et concours d'entree. Admission en L3 : "
            "BAC+2 universitaire ou BTS tertiaire sur concours."
        ),
    },
    {
        "code": "LECO",
        "nom": "Logistique et E-Commerce",
        "niveau": "MASTER",
        "duree": "Bac+5 - Master professionnel",
        "ordre": 20,
        "description": (
            "Master professionnel pour piloter les operations logistiques et les "
            "ecosystemes e-commerce. Admission en M1 : voie directe pour les titulaires "
            "de L3 e-logistique/marketing et concours pour les Licences 3 universitaires."
        ),
    },
    {
        "code": "FMER",
        "nom": "Finance et Management des Entreprises du Risque",
        "niveau": "MASTER",
        "duree": "Bac+5 - Master professionnel",
        "ordre": 21,
        "description": (
            "Master professionnel centre sur la finance, le pilotage des risques et la "
            "gestion de la performance. Admission en M1 : voie directe pour les L3 "
            "Finance Digitale et concours pour les L3 Economie/Gestion."
        ),
    },
    {
        "code": "MDEB",
        "nom": "Marketing Digital et E-Business",
        "niveau": "MASTER",
        "duree": "Bac+5 - Master professionnel",
        "ordre": 22,
        "description": (
            "Master professionnel pour concevoir des strategies de croissance digitale, "
            "de commerce electronique et de pilotage marketing. Admission en M1 : voie "
            "directe pour les L3 marketing, developpement applicatif ou finance digitale, "
            "et concours pour les profils sciences et technologies."
        ),
    },
    {
        "code": "TNOR",
        "nom": "Transformation Numerique des Organisations",
        "niveau": "MASTER",
        "duree": "Bac+5 - Master professionnel",
        "ordre": 23,
        "description": (
            "Master professionnel axe sur la conduite du changement, l'urbanisation des "
            "processus et la transformation numerique des organisations publiques et "
            "privees."
        ),
    },
    {
        "code": "MS-REGNUM",
        "nom": "Mastere Specialise en Regulation du Numerique",
        "niveau": "MASTER",
        "duree": "Mastere specialise - Bac+5",
        "ordre": 24,
        "description": (
            "Programme de reference co-diplomant avec Telecom Paris pour les cadres des "
            "autorites de regulation et des ministeres en Afrique. Le parcours couvre la "
            "regulation du numerique, la gouvernance sectorielle et les politiques "
            "publiques du digital."
        ),
    },
]


def seed_formations(apps, schema_editor):
    Filiere = apps.get_model("formations", "Filiere")

    for item in FORMATIONS:
        Filiere.objects.update_or_create(
            code=item["code"],
            defaults={
                "nom": item["nom"],
                "niveau": item["niveau"],
                "duree": item["duree"],
                "description": item["description"],
                "ordre": item["ordre"],
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("formations", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_formations, migrations.RunPython.noop),
    ]
