# Generated by Django 4.2.30 on 2026-04-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='video_type',
            field=models.CharField(blank=True, choices=[('upload', 'Upload'), ('youtube', 'YouTube')], max_length=20),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='file',
            field=models.FileField(blank=True, upload_to='media/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='image', max_length=10),
        ),
    ]
