# Generated by Django 4.2.30 on 2026-04-22 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossier_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('submitted', 'Soumis'), ('under_review', "En cours d'examen"), ('accepted', 'Accepte'), ('rejected', 'Refuse')], default='submitted', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=150)),
                ('nationality', models.CharField(choices=[('BJ', 'Benin'), ('BF', 'Burkina Faso'), ('CI', "Cote d'Ivoire"), ('ML', 'Mali'), ('MR', 'Mauritanie'), ('NE', 'Niger'), ('SN', 'Senegal'), ('TG', 'Togo'), ('OTHER', 'Autre')], max_length=10)),
                ('residence_country', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='inscriptions/photos/')),
                ('highest_degree', models.CharField(choices=[('BAC', 'Bac'), ('BAC_1', 'Bac+1'), ('BAC_2', 'Bac+2'), ('BTS_DUT', 'BTS / DUT'), ('LICENCE', 'Licence'), ('MASTER', 'Master'), ('DOCTORAT', 'Doctorat'), ('OTHER', 'Autre')], max_length=20)),
                ('institution_name', models.CharField(max_length=200)),
                ('graduation_year', models.PositiveIntegerField()),
                ('diploma_country', models.CharField(max_length=100)),
                ('transcript_file', models.FileField(upload_to='inscriptions/documents/transcripts/')),
                ('diploma_file', models.FileField(upload_to='inscriptions/documents/diplomas/')),
                ('motivation_file', models.FileField(blank=True, upload_to='inscriptions/documents/motivation/')),
                ('professional_experience', models.TextField(blank=True)),
                ('motivation_text', models.TextField(blank=True)),
                ('accuracy_certified', models.BooleanField(default=False)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='formations.filiere')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidatureDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='inscriptions/documents/additional/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='inscriptions.candidature')),
            ],
            options={
                'verbose_name': 'Document complementaire',
                'verbose_name_plural': 'Documents complementaires',
                'ordering': ['created_at'],
            },
        ),
    ]
